server {
    listen 80;
    server_name ${APP_HOST};
    index index.php index.html index.htm;
    root ${APP_PATH}/public;

    # Лимиты
    client_max_body_size 100M;
    client_body_timeout 60s;

    # Логи (рекомендуется)
    access_log /var/log/nginx/${APP_HOST}_access.log;
    error_log /var/log/nginx/${APP_HOST}_error.log;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~* ^/wp-content/uploads/.*\.php$ {
        deny all;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
